Repository Foxterosa/Paradise, pull requests merged in 2020-04, with the labels that each got.

#3 Panqueques, pan de miel y pastel de miel, junto un pequeño fix de traducción.
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/foods/baked_goods.dm
  code/modules/food_and_drinks/recipes/recipes_oven.dm
  icons/obj/food/food.dmi
Labels: Característica, Fix, Traducción

#7 Bebidas
  icons/obj/bebidas.dmi
  icons/turf/floors.dmi
Labels: Característica, Fix

#9 Niveles de alerta, cambio de acceso
  code/game/machinery/computer/communications.dm
Labels: Fix

#11 Cambios en cargo
  _maps/map_files/cyberiad/cyberiad.dmm
Labels: Característica

#12 Fix bug explosiones blancas.
  icons/turf/floors.dmi
Labels: Fix

#13 edito sprites
  icons/obj/butts.dmi
  icons/obj/contraband.dmi
Labels: Característica

#16 Paradise update 25 4 20 re
  .travis.yml
  _build_dependencies.sh
  _maps/test_all_maps.dm
  _maps/travis_map_testing.dm
  code/__DEFINES/logs.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/icons.dm
  code/datums/ai_laws.dm
  code/datums/diseases/critical.dm
  code/game/gamemodes/miniantags/guardian/guardian.dm
  code/game/gamemodes/wizard/rightandwrong.dm
  code/game/machinery/camera/presets.dm
  code/game/objects/items/weapons/tanks/watertank.dm
  code/modules/client/client procs.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/under/jobs/plasmamen/civilian_service.dm
  code/modules/clothing/under/jobs/plasmamen/engineering.dm
  code/modules/clothing/under/jobs/plasmamen/medsci.dm
  code/modules/clothing/under/jobs/plasmamen/security.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species/slime.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/modular_computers/computers/item/laptop.dm
  code/modules/power/singularity/particle_accelerator/particle.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  goon/browserassets/html/browserOutput.html
  goon/browserassets/js/unicode_9_annotations.js
  goon/code/datums/browserOutput.dm
  icons/mob/species/vox/suit.dmi
  install-byond.sh
  nano/templates/law_manager.tmpl
  tools/travis/build_nanoui.sh
  tools/travis/check_changelogs.sh
  tools/travis/check_grep.sh
  tools/travis/dm.sh
  tools/travis/install_build_deps.sh
  tools/travis/install_byond.sh
  tools/travis/json_verifier.py
Labels: Característica, invalid

#18 Acceso de Jefe de Personal, IA Upload, removido
  code/game/jobs/job/supervisor.dm
Labels: Fix

#17 Comida traducción part 0,5.
  code/modules/food_and_drinks/food/foods/desserts.dm
  code/modules/food_and_drinks/food/foods/pizza.dm
Labels: invalid
